
package com.trm.entity.exception;

import javax.xml.ws.WebFault;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-06-15T10:58:04.712+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "BusinessException", targetNamespace = "http://server.webservice.trm.com/")
public class BusinessException_Exception extends Exception {

    private static final long serialVersionUID = 1L;
    private BusinessException businessException;

    public BusinessException_Exception() {
        super();
    }

    public BusinessException_Exception(String message) {
        super(message);
    }

    public BusinessException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public BusinessException_Exception(String message, BusinessException businessException) {
        super(message);
        this.businessException = businessException;
    }

    public BusinessException_Exception(String message, BusinessException businessException, Throwable cause) {
        super(message, cause);
        this.businessException = businessException;
    }

    public BusinessException getFaultInfo() {
        return this.businessException;
    }
}
